# Generated by Django 5.0.1 on 2024-01-13 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=70)),
                ('collegeName', models.CharField(max_length=100)),
                ('graduationYear', models.IntegerField(blank=True, default=1)),
                ('dob', models.DateField(blank=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=15)),
                ('referralCode', models.CharField(blank=True, max_length=10)),
                ('myReferralCode', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.event')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
